### ISSUE TITLE
Can you provide the best co-lambda for cifar-10 and cifai-100, please

### ISSUE THREAD

**Issue by tzhxs** [hongxin001/JoCoR#1]

**Comment by hongxin001** [comment]
Actually, it depends on the datasets, noisy rate and basic models. Generally, the best lambda is between 0.5-0.9;

For example, in my experiment, the best lambda for CIFAR10 with 50% noise is 0.9. When it comes to 80% noise, the best is 0.65.

If you change the basic model to ResNet or others, you need to try different lambda for the best.
