### ISSUE TITLE
The default args of Clothing1M.

### ISSUE THREAD

**Issue by kovelxyz** [hongxin001/JoCoR#13]
Dear Hongxin Wei,

Thanks for providing the code.
I want to test the performance of JoCoR on Clothing1M, can you provide the default values for noise_rate and forget_rate?

Thank you so much.

**Comment by hongxin001** [comment]
Sorry for the late reply. You only need to set a value for noise_rate, for example, 20% or 40%.

**Comment by Rookie-wangf** [comment]
Dear Hongxin Wei,

Thanks for providing the code.
Now I want to use your network to train clothing1m dataset but I can't download his dataset, I want you to tell me where to go where I can download it.

Thank you so much.

**Comment by hongxin001** [comment]
Hi,

As mentioned by https://github.com/Cysu/noisy_label, you may contact tong.xiao.work[at]gmail[dot]com to get the download link.

**Comment by Rookie-wangf** [comment]
Thank you very much for your reply!
