### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [hongxin001/JoCoR#14]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set)?

Thanks!

**Comment by hongxin001** [comment]
Sorry for the late reply. 

1. I'm not sure if the proposed method can work on tabular data, but it should be consistent if you use neural networks. 

2. Sure. You may use the small loss criteria to select the noisy instances.
