### ISSUE TITLE
The inference of the model

### ISSUE THREAD

**Issue by GhostQ99** [hongxin001/JoCoR#15]
Deeply inspired by your work, but still got a little confused.  As given two networks, how to infer the prediction then? Choose any one of them? Also, is the result calculated based on the mean accuracy of the two networks? Or do we have to fuse the feature output by networks and then do classification?
Thank you~

**Comment by hongxin001** [comment]
Hi, Thanks for your interest. As the two networks are encouraged to be similar in the training, so you can use any one of them during testing.
