### ISSUE TITLE
Data normalisation

### ISSUE THREAD

**Issue by kilianFatras** [hongxin001/JoCoR#2]
Hello ! Thank you very much for the code release. i came across it and I do not find the data normalisation of CIFAR10 and CIFAR100. Could you point it to me please ? Thanks.

**Comment by hongxin001** [comment]
I don't use normalization for cifar10 in the setting of this work, following Coteaching. You can add it in the dataloader easily and you can expect a better result for our method and all baselines.

**Comment by kilianFatras** [comment]
Perfect ! Thank you for your answer !
