### ISSUE TITLE
What is the optimum parameter in MNIST.

### ISSUE THREAD

**Issue by daikiokamura** [hongxin001/JoCoR#6]
Dear Hongxin Wei,

My deepest thanks for providing the code.
Could you tell me the optimum lambda in MNIST?
Sorry to ask this of you when you are busy but I appreciate your help.

Thanks so much.

**Comment by hongxin001** [comment]
Hi, you can refer to the results of the Parameter Sensitivity Analysis in the appendix.

**Comment by daikiokamura** [comment]
I appreciate your quick answer. 
Thanks so much.
