### ISSUE TITLE
精度问题

### ISSUE THREAD

**Issue by lihuikenny** [hongxin001/JoCoR#7]
直接运行您的代码，我发现在Symmetry-50%的条件下，无非获得和论文一样的精度，最多只能到76%左右，请问是什么原因呢？其次论文中比如：在Symmetry-50%条件下，co_teaching+ 的效果为什么会比co_teaching效果还差，而且差很多，非常希望得到回复！感谢

**Comment by hongxin001** [comment]
你好，

1. 你应该没有设置lambda参数，而是直接使用默认参数训练。按照readme中推荐的参数训练，可以完整复现论文结果。

2. 在论文中related work以及experiment result中都有进行分析，直观上原因是co_teaching+的两次筛选留下的样本太少，导致很难训练到好的效果。

**Comment by lihuikenny** [comment]
> 你好，
> 
> 1. 你应该没有设置lambda参数，而是直接使用默认参数训练。按照readme中推荐的参数训练，可以完整复现论文结果。
> 2. 在论文中related work以及experiment result中都有进行分析，直观上原因是co_teaching+的两次筛选留下的样本太少，导致很难训练到好的效果。

你好，
    非常感谢你的回复！另外我有个问题想请教一下。我看您训练的代码的实现，发现loss只是在其中一个模型回传，也就是说您只更新了其中一个模型（loss_jocor中返回的两个loss是相同的，train的过程中也只有loss_1 backward）这样理解对吗？如果对，那么两个模型一起更新loss backward，那和《deep  mutual learning》这paper有什么区别和联系呢？谢谢！

**Comment by hongxin001** [comment]
不对，这个loss是对两个网络一起更新

**Comment by Chen-Song** [comment]
@lihuikenny 你好，我看了一下，《deep mutual learning》是两个网络迭代更新，JoCoR是两个网络算出来loss一起更新。其他的好像都是一样的了。关于更加深层次的区别和联系还不太清楚。
