### ISSUE TITLE
Noise type

### ISSUE THREAD

**Issue by ximingxing** [hongxin001/JoCoR#8]
https://github.com/hongxin001/JoCoR/blob/35eb5cd54f5508d17c5ead63bb9547f6e96dd871/data/utils.py#L289
https://github.com/hongxin001/JoCoR/blob/35eb5cd54f5508d17c5ead63bb9547f6e96dd871/data/utils.py#L293
What's the difference between pairflip and Asymmetric Flipping？

**Comment by hongxin001** [comment]
You may check [Co-teaching](https://arxiv.org/abs/1804.06872) to understand pariflip noise.
